### ISSUE TITLE
Plz Fix this bug

### ISSUE THREAD

**Issue by WebSmith72** [WebSmith72/Food-Delievery-Website#1]
when we click on "contact us" option, page opens and after entering all information by user, upon clicking submit button, no "thank you" window opens.

**Comment by SahilAgrwl** [comment]
Fix the bug by entering the following code in javascript file 👍

function myfunction() {
 alert ("Thank You")
}

**Comment by WebSmith72** [comment]
Thank You for suggesting code. We have resolved the issue by adding above code in file.

**Comment by SahilAgrwl** [comment]
I have resolved your issue. Plz review and merge my PR.

**Comment by WebSmith72** [comment]
We have reviewed your PR and finally merged it in our main branch. Thank you for contributing in our code.
